openapi: 3.2.0
info:
  title: Authentication Token API
  description: Spare api authentication API documentation
  termsOfService: https://terms.tryspare.com/en
  contact:
    name: Spare Technologies WLL.
    email: hello@tryspare.com
  license:
    name: Spare Technologies WLL.
  version: '1.0'
tags:
- name: Token
paths:
  /api/v1.0/authentication/Token:
    get:
      tags:
      - Token
      summary: Generates an API authentication token using the provided API credentials
      description: '**Unique resource name:** api_authentication.v1.token


        This endpoint authenticates an API keys by validating the provided API credentials.

        Upon successful authentication, an access token is generated and returned.


        **Authentication Process:**

        - The `app-id` and `x-api-key` headers must contain valid credentials.

        - If authentication is successful, a signed JSON Web Token (JWT) is issued.

        - If authentication fails due to invalid credentials, a `401 Unauthorized` response is returned.


        **Security Considerations:**

        - The API key (`x-api-key`) should be kept confidential.

        - The generated JWT should be used for subsequent authenticated requests.'
      parameters:
      - name: app-id
        in: header
        description: The unique identifier of the API keys.
        required: true
        schema:
          type: string
      - name: x-api-key
        in: header
        description: The API key associated with the API keys.
        required: true
        schema:
          type: string
      responses:
        '401':
          description: Returned if the API credentials (`app-id` and `x-api-key`) are incorrect or unauthorized.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '500':
          description: Internal Server Error
        '200':
          description: Successfully generated an API authentication token.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JsonWebTokenResponseModel'
      operationId: getApiV10AuthenticationToken
      x-operation-id-source: derived
  /api/v1.0/authentication/Refresh:
    get:
      tags:
      - Token
      summary: Refreshes an API authentication token using a valid refresh token
      description: '**Unique resource name:** api_authentication.v1.refresh


        This endpoint allows clients to obtain a new access token by providing a valid refresh token.

        The refresh token must be issued by the authentication service and must not be expired.


        **Authentication Process:**

        - The `refresh-token` header must contain a valid refresh token.

        - If the refresh token is valid, a new access token is issued.

        - If the refresh token is invalid or expired, a `401 Unauthorized` response is returned.


        **Security Considerations:**

        - Refresh tokens should be stored securely and not shared.'
      parameters:
      - name: refresh-token
        in: header
        description: The refresh token used to obtain a new access token.
        required: true
        schema:
          type: string
      responses:
        '401':
          description: Returned if the refresh token is incorrect, expired, or unauthorized.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '500':
          description: Internal Server Error
        '200':
          description: Successfully generated a new API authentication token.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JsonWebTokenResponseModel'
      operationId: getApiV10AuthenticationRefresh
      x-operation-id-source: derived
components:
  schemas:
    JsonWebTokenResponseModel:
      type: object
      properties:
        type:
          type:
          - string
          - 'null'
          readOnly: true
        access_token:
          type:
          - string
          - 'null'
        expires_in:
          type: integer
          format: int32
        refresh_token:
          type:
          - string
          - 'null'
        refresh_expires_in:
          type: integer
          format: int32
      additionalProperties: false
    ProblemDetails:
      type: object
      properties:
        type:
          type:
          - string
          - 'null'
        title:
          type:
          - string
          - 'null'
        status:
          type:
          - integer
          - 'null'
          format: int32
        detail:
          type:
          - string
          - 'null'
        instance:
          type:
          - string
          - 'null'
      additionalProperties: {}
