openapi: 3.2.0
info:
  title: Authentication Cert API
  description: Spare api authentication API documentation
  termsOfService: https://terms.tryspare.com/en
  contact:
    name: Spare Technologies WLL.
    email: hello@tryspare.com
  license:
    name: Spare Technologies WLL.
  version: '1.0'
tags:
- name: Cert
paths:
  /api/v1.0/authentication/Jwks:
    get:
      tags:
      - Cert
      summary: Retrieves the JSON Web Key Set (JWKS) used for token, payloads and webhook…
      description: '**Unique resource name:** api_authentication.v1.cert.jwks


        This endpoint provides a set of JSON Web Keys (JWK) as defined in

        RFC 7517.


        **Usage:**

        - Used to verify the signature of access tokens and refresh tokens.

        - Used to validate the `x-signature` header in the API responses or webhook events.

        - Ensures secure cryptographic verification of API interactions.


        The response includes RSA and ECC-based public keys required for token and data signature validation.'
      responses:
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '500':
          description: Internal Server Error
        '200':
          description: '- Successfully returns the JSON Web Key Set.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SpJsonWebKeySet'
      operationId: getApiV10AuthenticationJwks
      x-operation-id-source: derived
components:
  schemas:
    SpJsonWebKey:
      type: object
      properties:
        p:
          type:
          - string
          - 'null'
        kty:
          type:
          - string
          - 'null'
        q:
          type:
          - string
          - 'null'
        d:
          type:
          - string
          - 'null'
        e:
          type:
          - string
          - 'null'
        use:
          type:
          - string
          - 'null'
        kid:
          type:
          - string
          - 'null'
        qi:
          type:
          - string
          - 'null'
        dp:
          type:
          - string
          - 'null'
        alg:
          type:
          - string
          - 'null'
        dq:
          type:
          - string
          - 'null'
        n:
          type:
          - string
          - 'null'
        x:
          type:
          - string
          - 'null'
        y:
          type:
          - string
          - 'null'
        crv:
          type:
          - string
          - 'null'
        x5t:
          type:
          - string
          - 'null'
        x5c:
          type:
          - array
          - 'null'
          items:
            type: string
      additionalProperties: false
    ProblemDetails:
      type: object
      properties:
        type:
          type:
          - string
          - 'null'
        title:
          type:
          - string
          - 'null'
        status:
          type:
          - integer
          - 'null'
          format: int32
        detail:
          type:
          - string
          - 'null'
        instance:
          type:
          - string
          - 'null'
      additionalProperties: {}
    SpJsonWebKeySet:
      type: object
      properties:
        keys:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/SpJsonWebKey'
      additionalProperties: false
